version = 0.1

[default.global.parameters]
stack_name = "cryfs-web-backend"

[default.build.parameters]
cached = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
region = "us-east-1"
